### ISSUE TITLE
Compliler warnings

### ISSUE THREAD

**Issue by fela98** [doxiaodong/intercept-fetch#3]
I get the following warning for a couple of files when using this module:
`WARNING in ./~/intercept-fetch/index.js
(Emitted value instead of an instance of Error) Cannot find source file 'index.ts': Error: Can't resolve './index.ts' in '[...]/node_modules/intercept-fetch'`

**Comment by doxiaodong** [comment]
What is your environment? It should resolve `index.d.ts` with typescript or resolve `index.js` with javascript

**Comment by doxiaodong** [comment]
`"sources":["index.ts"]` in `index.js.map`. It should not resolve the sources key. What is the sourcemap  you use?

**Comment by doxiaodong** [comment]
fix this after v1.3.3 @fela98
